Cherry pick of 7ec7615bd4cc14a97e7dce1328a656c5f298c51d failed
stdout:
Auto-merging account_multi_store/__manifest__.py
CONFLICT (content): Merge conflict in account_multi_store/__manifest__.py

stderr:
23:09:00.143478 git.c:439               trace: built-in: git cherry-pick 7ec7615bd4cc14a97e7dce1328a656c5f298c51d
error: could not apply 7ec7615... [IMP] account_ms: add option to force reconcile only on same store
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: